### ISSUE TITLE
ShadowNAND paths

### ISSUE THREAD

**Issue by RShadowhand** [d0k3/A9NC#1]
ShadowNAND will load `SD:/homebrew/a9nc.bin` and then remove it once it has been booted with the latest commit.

EDIT: Don't go forward with this because to support A9NC I broke sd-less boot, so I'll be reverting it for the time being.

**Comment by d0k3** [comment]
Added in https://github.com/d0k3/A9NC/commit/c69b91d02140477ea80643fd6823044949cfc3be
