### ISSUE TITLE
[Not an issue but something to do with A9NC] My Luma3DS fork and new ShadowNAND location

### ISSUE THREAD

**Issue by NightScript370** [d0k3/A9NC#4]
So my Luma3DS fork remaps from `luma\payloads` to `homebrew\3ds\payloads` in order to make my SD card root clean. In the ReadME, it says that Developers should contact you if you need to add a path to it. So, can you add `homebrew\3ds\payloads\` to your path?
## 

Also, ShadowNAND has now a new path: `homebrew\3ds\`. So can you change it to that?

Thank you in advance.

--Maorninja322

(PS: I don't know how to add a tag so I just wrote in a box. Sorry.)

**Comment by d0k3** [comment]
Well... that's your fork atm, which isn't by any means a standard. And Luma3DS actually has multiple payload destinations (accessed by arrows/X/Y). You can just wait, but if you want anything fast, I suggest you fork yourself and change this:
https://github.com/d0k3/A9NC/blob/master/source/main.c#L18-L19

I'll discuss this with @RShadowhand, any standard work folder changes will come later.
