### ISSUE TITLE
Lost a9nc.bin?

### ISSUE THREAD

**Issue by NinjaBoyLao** [d0k3/A9NC#5]
I might just be really stupid, but I'm using a bootloader (hartmannaf's BootCTR9) and i haven't found a single a9nc.bin anywhere in the latest release (0.0.9 at writing). yet you've said it's path can be /a9nc.bin, which the bootloader would support, if i had it. i don't really know for sure how to compile this from source, am i expected to do that to get the binary?

**Comment by d0k3** [comment]
Well, this can write to /a9nc.bin (selected via L button) and you can just use the release from here. Does that solve it for you?

**Comment by d0k3** [comment]
Assumed solved, I checked
